### ISSUE TITLE
issue when running the example quantum_neural_network.py

### ISSUE THREAD

**Issue by MichelNowak1** [XanaduAI/strawberryfields#271]
#### Issue description

When the example of strawberryfields quantum_neural_network.py is run, it breaks when calling the Dgate in ops.py. After a git bissect, one finds that the problem comes from the commit:
 94036642f3008bfa7202774a51b907ba51f35138 Symbolic Operation parameters using SymPy.
It seems that the wrapper around the exp function is not working correctly.

* *Expected behavior:* quantum_neural_network.py should return (result thrown by SF when checking out to the first commit before the commit that broke the example):
```
Beginning optimization
Fidelity before optimization: 4.7938176e-08
Fidelity after optimization: 0.9851418

Target state: [0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
Output state: [ 0.   +0.001j  0.993-0.001j  0.   +0.001j -0.   -0.001j  0.   +0.j
 -0.   +0.j   ]
```

* *Actual behavior:* (What actually happens)
Nothing happens: see the traceback below

* *Reproduces how often:* Always

* *System information:*
Strawberry Fields: a Python library for continuous-variable quantum circuits.
Copyright 2018-2019 Xanadu Quantum Technologies Inc.
Python version:            3.6.8
Platform info:             Linux-5.0.0-37-generic-x86_64-with-Ubuntu-18.04-bionic
Installation path:         /home/michel/codes/strawberryfields/strawberryfields
Strawberry Fields version: 0.12.0
Numpy version:             1.17.4
Scipy version:             1.3.1
The Walrus version:           0.9.0
Blackbird version:         0.2.1
TensorFlow version:        1.3.0

#### Source code and tracebacks

```
Traceback (most recent call last):
  File "quantum_neural_network.py", line 99, in <module>
    results = eng.run(qnn, run_options={"eval": False})
  File "/home/michel/codes/strawberryfields/strawberryfields/engine.py", line 481, in run
    result = super()._run(program, args=args, compile_options=compile_options, **eng_run_options)
  File "/home/michel/codes/strawberryfields/strawberryfields/engine.py", line 349, in _run
    self._run_program(p, **kwargs)
  File "/home/michel/codes/strawberryfields/strawberryfields/engine.py", line 423, in _run_program
    cmd.op.apply(cmd.reg, self.backend, **kwargs)  # NOTE we could also handle storing measured vals here
  File "/home/michel/codes/strawberryfields/strawberryfields/ops.py", line 470, in apply
    self._apply(temp, backend, **kwargs)
  File "/home/michel/codes/strawberryfields/strawberryfields/ops.py", line 920, in _apply
    z = p[0] * np.exp(1j * p[1])
  File "/home/michel/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 880, in r_binary_op_wrapper
    x = ops.convert_to_tensor(x, dtype=y.dtype.base_dtype, name="x")
  File "/home/michel/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 611, in convert_to_tensor
    as_ref=False)
  File "/home/michel/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 676, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/michel/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 121, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/michel/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/michel/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 376, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/michel/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected float32, got 1j of type 'complex' instead.
```

**Comment by co9olguy** [comment]
Thanks for the detailed bug report @MichelNowak1 
We'll look into it asap

**Comment by MichelNowak1** [comment]
Actually, it's just a problem of having a tensor of type float32 multiplied by 1j, a complex number.

Changing np.exp to tf.exp and adding the line `p = tf.cast(p, tf.complex128)` in the apply function of the Dgate in ops.py (line 920 at tag 0.12.0) solved the issue.
```
def _apply(self, reg, backend, **kwargs):
    p = par_evaluate(self.p)
    p = tf.cast(p, tf.complex128)
    z = p[0] * tf.exp(1j * p[1])
    backend.displacement(z, *reg)
```
Not sure if its the way to go though...

**Comment by glassnotes** [comment]
Closing this as the demos were all recently tested and this one runs smoothly under the development version of PennyLane (0.14). Please feel free to re-open if this issue persists.
